-- Retail Sales Analysis Queries
-- Project: Smart Retail Intelligence Dashboard
-- Purpose: To analyze sales performance and customer behavior
-- Author: <Your Name>

-- NOTE:
-- The retail data has been loaded into a table called `sales`.
-- These queries were used to validate data, calculate KPIs,
-- and derive insights before building the Power BI dashboard.


/* --------------------------------------------------
   Basic data understanding
   -------------------------------------------------- */

-- Total number of sales transactions
SELECT COUNT(*) AS total_transactions
FROM sales;

-- Number of unique customers
SELECT COUNT(DISTINCT customer_id) AS unique_customers
FROM sales;

-- Time period covered by the data
SELECT 
    MIN(date) AS first_transaction_date,
    MAX(date) AS last_transaction_date
FROM sales;


/* --------------------------------------------------
   Key business KPIs
   -------------------------------------------------- */

-- Overall revenue generated
SELECT SUM(total_amount) AS total_revenue
FROM sales;

-- Total profit earned
SELECT SUM(estimated_profit) AS total_profit
FROM sales;

-- Average order value
SELECT AVG(total_amount) AS average_order_value
FROM sales;

-- Profit margin calculation
SELECT 
    SUM(estimated_profit) / SUM(total_amount) AS profit_margin
FROM sales;


/* --------------------------------------------------
   Time-based sales analysis
   -------------------------------------------------- */

-- Monthly revenue trend
SELECT 
    strftime('%Y-%m', date) AS year_month,
    SUM(total_amount) AS monthly_revenue
FROM sales
GROUP BY year_month
ORDER BY year_month;


/* --------------------------------------------------
   Product category performance
   -------------------------------------------------- */

-- Revenue contribution by product category
SELECT 
    product_category,
    SUM(total_amount) AS total_revenue
FROM sales
GROUP BY product_category
ORDER BY total_revenue DESC;

-- Profit contribution by product category
SELECT 
    product_category,
    SUM(estimated_profit) AS total_profit
FROM sales
GROUP BY product_category
ORDER BY total_profit DESC;


/* --------------------------------------------------
   Customer segmentation analysis
   -------------------------------------------------- */

-- Customer count by gender
SELECT 
    gender,
    COUNT(DISTINCT customer_id) AS customer_count
FROM sales
GROUP BY gender;

-- Revenue generated by different age groups
SELECT 
    age_group,
    SUM(total_amount) AS total_revenue
FROM sales
GROUP BY age_group
ORDER BY total_revenue DESC;


/* --------------------------------------------------
   High-value customers
   -------------------------------------------------- */

-- Top 10 customers based on total spending
SELECT 
    customer_id,
    SUM(total_amount) AS total_spent
FROM sales
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 10;


/* --------------------------------------------------
   Business insight queries
   -------------------------------------------------- */

-- Categories with relatively low profit margins
SELECT 
    product_category,
    SUM(total_amount) AS revenue,
    SUM(estimated_profit) AS profit,
    SUM(estimated_profit) / SUM(total_amount) AS profit_margin
FROM sales
GROUP BY product_category
ORDER BY profit_margin ASC;
